services:
  easy:
    build: .
    ports:
      - "8080:8080"
    environment:
      PLANTUML_URL: http://plantuml:8080
    volumes:
      - ./model.db:/app/model.db
    depends_on:
      - plantuml

  plantuml:
    image: plantuml/plantuml-server:jetty
